### ISSUE TITLE
npm install has warnings

### ISSUE THREAD

**Issue by AndriyLantukh** [qualityshepherd/protractor_example#1]
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

as result non all dependencies instals 
and when I try to run test I got

Error: No selenium server jar found at the specified location (/Development/Workspase/protractor_example/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar). Check that the version number is up to date.

**Comment by qualityshepherd** [comment]
I removed this at some point.
